package src

type Quote struct {
	Used           bool
	Quote_english  string
	Quote_japanese string
}

var Quote_bank = []Quote{
	{Quote_english: "The best way to predict the future is to create it.", Quote_japanese: "未来を予測する最良の方法は、それを創造することです。"},
	{Quote_english: "Do what you can, with what you have, where you are.", Quote_japanese: "できることを、あるもので、いる場所でやりなさい。"},
	{Quote_english: "It always seems impossible until it’s done.", Quote_japanese: "成し遂げるまでは、いつも不可能に見える。"},
	{Quote_english: "Happiness depends upon ourselves.", Quote_japanese: "幸せは自分自身にかかっている。"},
	{Quote_english: "Turn your wounds into wisdom.", Quote_japanese: "傷を知恵に変えなさい。"},
	{Quote_english: "The harder you work for something, the greater you’ll feel when you achieve it.", Quote_japanese: "努力すればするほど、達成したときの喜びは大きくなる。"},
	{Quote_english: "Don’t count the days, make the days count.", Quote_japanese: "日々を数えるのではなく、日々を意味あるものにしなさい。"},
	{Quote_english: "Your limitation—it’s only your imagination.", Quote_japanese: "限界とは、あなたの想像にすぎない。"},
	{Quote_english: "Dream bigger. Do bigger.", Quote_japanese: "もっと大きな夢を持ち、もっと大きな行動を起こしなさい。"},
	{Quote_english: "Sometimes later becomes never. Do it now.", Quote_japanese: "時には『あとで』が『決して』になってしまう。今やりなさい。"},
	{Quote_english: "Fall down seven times, stand up eight.", Quote_japanese: "七転び八起き"},
	{Quote_english: "Kappa swept away by the river.", Quote_japanese: "河童の川流れ"},
	{Quote_english: "Fishing bream with shrimp as bait.", Quote_japanese: "海老で鯛を釣る"},
	{Quote_english: "Boil and drink dirt underneath the fingernails.", Quote_japanese: "爪の垢を煎じて飲む"},
	{Quote_english: "Dumplings over flowers.", Quote_japanese: "餃子は花よりも優れています"},
	{Quote_english: "Work in the fields on a fine day, read books on a rainy day.", Quote_japanese: "晴耕雨読"},
	{Quote_english: "The talented hawk hides its claws.", Quote_japanese: "能ある鷹は爪を隠す"},
	{Quote_english: "A pearl to a pig.", Quote_japanese: "豚に真珠"},
	{Quote_english: "If a fish is kind to the water, the water will be kind to the fish.", Quote_japanese: "魚心あれば水心"},
	{Quote_english: "To lose is to win.", Quote_japanese: "負けるが勝ち"},
	{Quote_english: "A skilled swordsman has superior manners.", Quote_japanese: "刃に強き者は礼にすぐる"},
	{Quote_english: "It’s easier to give birth than to think about it.", Quote_japanese: "案ずるより産むが易し"},
	{Quote_english: "Love and coughing cannot be hidden.", Quote_japanese: "恋とせきとは隠されぬ"},
	{Quote_english: "Know the pain of others by pinching yourself.", Quote_japanese: "我が身をつねって人の痛さを知れ"},
	{Quote_english: "Flowers even bloom on grass that has been stomped on.", Quote_japanese: "踏まれた草にも花が咲く"},
	{Quote_english: "Hide your head but fail to hide your butt.", Quote_japanese: "頭隠して尻隠さず"},
	{Quote_english: "Once in a lifetime encounter.", Quote_japanese: "一期一会"},
	{Quote_english: "Even sea bream loses its flavor when eaten alone.", Quote_japanese: "鯛も一人はうまからず"},
	{Quote_english: "More haste, less speed.", Quote_japanese: "急がば回れ"},
	{Quote_english: "Better to ask and be embarrassed than not ask and never know.", Quote_japanese: "聞くは一時の恥聞かぬは一生の恥"},
	{Quote_english: "Good fences make good neighbors.", Quote_japanese: "親しき中にも礼儀あり"},
	{Quote_english: "Touch red pigment, become red.", Quote_japanese: "朱に交われば赤くなる"},
	{Quote_english: "What one likes, one will do well at.", Quote_japanese: "好きこそ物の上手なれ"},
	{Quote_english: "Self-work, self-profit.", Quote_japanese: "自業自得"},
	{Quote_english: "The journey of a thousand miles begins with a single step.", Quote_japanese: "千里の道も一歩から。"},
	{Quote_english: "If you believe, you can achieve.", Quote_japanese: "信じれば、成し遂げられる。"},
	{Quote_english: "Success is not final, failure is not fatal: It is the courage to continue that counts.", Quote_japanese: "成功は終わりではなく、失敗は致命的ではない。大切なのは続ける勇気である。"},
	{Quote_english: "The only way to do great work is to love what you do.", Quote_japanese: "素晴らしい仕事をする唯一の方法は、自分の仕事を愛することだ。"},
	{Quote_english: "In the middle of difficulty lies opportunity.", Quote_japanese: "困難の中に機会がある。"},
	{Quote_english: "Be the change you wish to see in the world.", Quote_japanese: "見たいと思う変化に、あなた自身がなりなさい。"},
	{Quote_english: "Life is what happens to you while you're busy making other plans.", Quote_japanese: "人生は、他の計画を立てている間に起こることだ。"},
	{Quote_english: "You miss 100% of the shots you don't take.", Quote_japanese: "打たないシュートは100％外れる。"},
	{Quote_english: "The purpose of our lives is to be happy.", Quote_japanese: "人生の目的は幸せになることです。"},
	{Quote_english: "Everything you can imagine is real.", Quote_japanese: "想像できることは、すべて現実である。"},
	{Quote_english: "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", Quote_japanese: "夢にしっかりとしがみつけ。なぜなら、夢が死んだら、人生は飛べない翼の折れた鳥となるからだ。"},
	{Quote_english: "Do not go where the path may lead, go instead where there is no path and leave a trail.", Quote_japanese: "道が導くかもしれない所へ行くな。代わりに道のない所へ行き、跡を残せ。"},
	{Quote_english: "Well begun is half done.", Quote_japanese: "始めが半分。"},
	{Quote_english: "The secret of getting ahead is getting started.", Quote_japanese: "前進する秘訣は、始めることだ。"},
	{Quote_english: "It's not the years in your life that count. It's the life in your years.", Quote_japanese: "大切なのは人生の年数ではなく、その年数の中の人生だ。"},
	{Quote_english: "Strive not to be a success, but rather to be of value.", Quote_japanese: "成功しようとするのではなく、価値のある人間になろうと努めなさい。"},
	{Quote_english: "I have not failed. I've just found 10,000 ways that won't work.", Quote_japanese: "私は失敗したのではない。ただ、うまくいかない1万通りの方法を見つけたのだ。"},
	{Quote_english: "A person who never made a mistake never tried anything new.", Quote_japanese: "一度も失敗をしたことがない人は、何も新しいことに挑戦したことがない人である。"},
	{Quote_english: "The only true wisdom is in knowing you know nothing.", Quote_japanese: "唯一の真の知恵は、自分が何も知らないと知っていることの中にある。"},
	{Quote_english: "He who has a why to live for can bear almost any how.", Quote_japanese: "生きる理由を持つ者は、ほとんどどのような方法でも耐えられる。"},
	{Quote_english: "Where there is love there is life.", Quote_japanese: "愛がある所に人生がある。"},
	{Quote_english: "The mind is everything. What you think you become.", Quote_japanese: "心がすべてである。あなたが思うものにあなたはなる。"},
	{Quote_english: "The best time to plant a tree was 20 years ago. The second best time is now.", Quote_japanese: "木を植えるのに一番良い時期は20年前だった。二番目に良い時期は今である。"},
	{Quote_english: "You must be the change you wish to see in the world.", Quote_japanese: "あなた自身が、世界に望む変化とならなければならない。"},
	{Quote_english: "An unexamined life is not worth living.", Quote_japanese: "吟味されない人生は生きる価値がない。"},
	{Quote_english: "Happiness is not something ready made. It comes from your own actions.", Quote_japanese: "幸せは既製品ではない。それはあなた自身の行動から来る。"},
	{Quote_english: "If you want to lift yourself up, lift up someone else.", Quote_japanese: "自分を持ち上げたいなら、他の誰かを持ち上げなさい。"},
	{Quote_english: "The only impossible journey is the one you never begin.", Quote_japanese: "唯一不可能な旅は、あなたが決して始めない旅である。"},
	{Quote_english: "Act as if what you do makes a difference. It does.", Quote_japanese: "あなたの行動が違いを生むかのように振る舞いなさい。それは違いを生む。"},
	{Quote_english: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", Quote_japanese: "限界は私たちの心の中にのみ存在する。しかし、想像力を使えば、可能性は無限大になる。"},
	{Quote_english: "Quality is not an act, it is a habit.", Quote_japanese: "質は行為ではなく、習慣である。"},
	{Quote_english: "The future belongs to those who believe in the beauty of their dreams.", Quote_japanese: "未来は、自分の夢の美しさを信じる者たちのものである。"},
	{Quote_english: "It is during our darkest moments that we must focus to see the light.", Quote_japanese: "まさに最も暗い瞬間に、私たちは光を見るために集中しなければならない。"},
	{Quote_english: "Whoever is happy will make others happy too.", Quote_japanese: "幸せな人は、他の人も幸せにする。"},
	{Quote_english: "Do not let making a living prevent you from making a life.", Quote_japanese: "生計を立てることが、人生を作ることを妨げるようにさせてはいけない。"},
	{Quote_english: "Even a journey of a thousand miles begins with a single step.", Quote_japanese: "千里の道も一歩から。"},
	{Quote_english: "Believe you can and you're halfway there.", Quote_japanese: "できると信じなさい。そうすれば、もう半分は達成したようなものだ。"},
	{Quote_english: "We can't help everyone, but everyone can help someone.", Quote_japanese: "私たちは皆を助けることはできないが、誰もが誰かを助けることはできる。"},
	{Quote_english: "The way to get started is to quit talking and begin doing.", Quote_japanese: "始める方法は、話すのをやめて、やり始めることだ。"},
	{Quote_english: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", Quote_japanese: "心の恐怖に振り回されるな。心の夢に導かれよ。"},
	{Quote_english: "The grass is always greener on the other side of the fence.", Quote_japanese: "隣の芝生は青い。"},
	{Quote_english: "When the winds of change blow, some people build walls and others build windmills.", Quote_japanese: "変化の風が吹くとき、壁を作る人もいれば、風車を作る人もいる。"},
	{Quote_english: "You are never too old to set another goal or to dream a new dream.", Quote_japanese: "新たな目標を設定したり、新たな夢を見たりするのに、年を取りすぎていることはない。"},
	{Quote_english: "The pain you feel today is the strength you feel tomorrow.", Quote_japanese: "今日あなたが感じる痛みは、明日あなたが感じる強さである。"},
	{Quote_english: "Nothing is impossible, the word itself says 'I'm possible'!", Quote_japanese: "不可能なものなどない。その言葉自体が『私は可能だ』と言っている！"},
	{Quote_english: "You define your own life. Don't let other people write your script.", Quote_japanese: "あなた自身の人生を定義するのはあなただ。他の人にあなたの脚本を書かせてはいけない。"},
	{Quote_english: "The only person you are destined to become is the person you decide to be.", Quote_japanese: "あなたがなる運命にある唯一の人は、あなたがなると決心した人である。"},
	{Quote_english: "Life is either a daring adventure or nothing at all.", Quote_japanese: "人生はどちらかの大胆な冒険であるか、さもなくば無である。"},
	{Quote_english: "You can't cross the sea merely by standing and staring at the water.", Quote_japanese: "ただ立って水をじっと見つめているだけで海を渡ることはできない。"},
	{Quote_english: "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.", Quote_japanese: "太陽自体も、最初に昇るときは弱く、日が進むにつれて力と勇気を集める。"},
	{Quote_english: "The only limit to our realization of tomorrow will be our doubts of today.", Quote_japanese: "明日の実現に対する唯一の限界は、今日の私たちの疑念である。"},
	{Quote_english: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", Quote_japanese: "私たちの内側にあるものと比べれば、私たちの後ろと前に横たわっているものは些細なことである。"},
	{Quote_english: "The greatest glory in living lies not in never falling, but in rising every time we fall.", Quote_japanese: "生きる上で最大の栄光は、決して転ばないことにあるのではなく、転ぶたびに起き上がることにある。"},
}
